export function buildAutomationBlueprints(projectKeys) {
  const scope = projectKeys.join(', ');

  return [
    {
      name: 'Notify assignee when an app-created issue becomes overdue',
      trigger: 'Hourly Forge scheduled check',
      condition: 'Issue belongs to an environment generated by this app, is unresolved, has an assignee, and its due date has passed',
      action: 'Send one Jira notification per crossed due-date and assignee combination, including once to a new assignee after reassignment',
      scope,
      implementation: 'forge-scheduled',
    },
    {
      name: 'Email assignee when priority is high',
      trigger: 'Priority changed or issue created',
      condition: 'Priority is Highest, High, or Critical and assignee is not empty',
      action: 'Send email to Assignee with the issue key, summary, priority, and due date',
      emailSubject: 'High priority issue assigned: {{issue.key}}',
      emailBody: [
        'Hi {{issue.assignee.displayName}},',
        '',
        '{{issue.key}} is {{issue.priority.name}} priority and is assigned to you.',
        '',
        'Summary: {{issue.summary}}',
        'Status: {{issue.status.name}}',
        'Due date: {{issue.duedate}}',
        'Link: {{issue.url}}',
      ].join('\n'),
      scope,
    },
    {
      name: 'Transition request when deployment status changes',
      trigger: 'Deployment status changed',
      condition: 'Deployment status is Completed, Failed, or Cancelled',
      action: 'Transition the related request according to the deployment result',
      scope,
    },
  ];
}
