const DEFAULT_GADGET_TITLES = {
  'forge-environment': 'Dashboard Summary',
  'forge-open-work': 'Open Work Details',
  'forge-status': 'Work by Status',
  'forge-priority': 'Work by Priority',
  'forge-overdue': 'Overdue and At-Risk Work',
  'forge-sprint-health': 'Sprint Health',
  'forge-sprint-burndown': 'Sprint Execution',
  'forge-roadmap': 'Upcoming Releases',
  'forge-average-time-status': 'Time in Status',
  'forge-ticket-aging': 'Aging Work',
  'forge-escalations': 'SLA and Escalation Risk',
  'forge-reports': 'Drilldowns and Knowledge',
  'forge-created-resolved': 'Created vs Resolved Trend',
  'forge-projects': 'Project Scope',
};

const DEFAULT_GADGET_VISUALS = {
  'forge-environment': 'kpi-scorecard',
  'forge-open-work': 'issue-table',
  'forge-status': 'stacked-bars',
  'forge-priority': 'donut',
  'forge-overdue': 'risk-bars',
  'forge-sprint-health': 'donut',
  'forge-sprint-burndown': 'column-chart',
  'forge-roadmap': 'timeline',
  'forge-average-time-status': 'duration-bars',
  'forge-ticket-aging': 'aging-bars',
  'forge-escalations': 'risk-donut',
  'forge-reports': 'drilldown-list',
  'forge-created-resolved': 'trend-bars',
  'forge-projects': 'portfolio-bars',
};

const ROLE_SECTION_LABELS = {
  'forge-environment': 'Executive KPI Header',
  'forge-open-work': 'Action Queue',
  'forge-status': 'Lifecycle Distribution',
  'forge-priority': 'Risk and Severity Mix',
  'forge-overdue': 'Aging and Breach Risk',
  'forge-sprint-health': 'Sprint Completion Health',
  'forge-sprint-burndown': 'Sprint / Flow Trend',
  'forge-roadmap': 'Calendar and Release Timeline',
  'forge-average-time-status': 'Time and Flow Efficiency',
  'forge-ticket-aging': 'Aging Distribution',
  'forge-escalations': 'SLA and Escalation Signals',
  'forge-reports': 'Drilldowns and Evidence',
  'forge-created-resolved': 'Demand vs Completion Trend',
  'forge-projects': 'Portfolio / Team Distribution',
};

const PROFILE_ROLE_OVERRIDES = {
  'service-desk-operations': {
    'forge-open-work': { visualType: 'queue-action-cards', title: 'Immediate Queue Actions', sectionLabel: 'Daily Triage Queue' },
    'forge-status': { visualType: 'queue-status-bars', title: 'Queue Status Balance', sectionLabel: 'Queue Health' },
    'forge-priority': { visualType: 'priority-donut', title: 'Tickets by Priority', sectionLabel: 'Priority Pressure' },
    'forge-ticket-aging': { visualType: 'aging-risk-bars', title: 'Aging Tickets', sectionLabel: 'Aging Risk' },
    'forge-escalations': { visualType: 'sla-risk-donut', title: 'SLA at Risk', sectionLabel: 'SLA Risk' },
    'forge-average-time-status': { visualType: 'response-time-bars', title: 'First Response / Handling Proxy', sectionLabel: 'Response Time Proxy' },
  },
  'agent-performance': {
    'forge-projects': { visualType: 'agent-workload-bars', title: 'Workload Distribution', sectionLabel: 'Agent Workload' },
    'forge-open-work': { visualType: 'agent-work-cards', title: 'Assigned Work Detail', sectionLabel: 'Agent Queue' },
    'forge-average-time-status': { visualType: 'handling-time-bars', title: 'Average Handling Time Proxy', sectionLabel: 'Handling Time' },
    'forge-status': { visualType: 'productivity-bars', title: 'Resolution Flow by Status', sectionLabel: 'Productivity Health' },
    'forge-created-resolved': { visualType: 'productivity-trend', title: 'Resolved Work Trend', sectionLabel: 'Productivity Trend' },
    'forge-priority': { visualType: 'quality-risk-donut', title: 'Reopen / Priority Risk Proxy', sectionLabel: 'Quality Signals' },
  },
  'sla-monitoring': {
    'forge-escalations': { visualType: 'sla-risk-donut', title: 'SLA Compliance Overview', sectionLabel: 'SLA Compliance' },
    'forge-overdue': { visualType: 'breach-bars', title: 'Breached Tickets by Project', sectionLabel: 'Breached Work' },
    'forge-ticket-aging': { visualType: 'approaching-breach-bars', title: 'Tickets Approaching Breach', sectionLabel: 'Approaching Breach' },
    'forge-average-time-status': { visualType: 'response-time-bars', title: 'Response and Resolution Time Proxy', sectionLabel: 'Time to Serve' },
    'forge-open-work': { visualType: 'breach-action-cards', title: 'SLA Follow-Up Queue', sectionLabel: 'Escalation Queue' },
  },
  'incident-management': {
    'forge-priority': { visualType: 'severity-donut', title: 'Incident Severity Distribution', sectionLabel: 'Severity Mix' },
    'forge-escalations': { visualType: 'incident-risk-donut', title: 'Escalated Incidents', sectionLabel: 'Escalation Risk' },
    'forge-status': { visualType: 'incident-lifecycle-bars', title: 'Incident Handling Flow', sectionLabel: 'Restoration Flow' },
    'forge-created-resolved': { visualType: 'incident-trend', title: 'Incident Resolution Trend', sectionLabel: 'Incident Trend' },
    'forge-ticket-aging': { visualType: 'major-incident-aging-bars', title: 'Aging Major Incidents', sectionLabel: 'Major Incident Aging' },
    'forge-open-work': { visualType: 'incident-action-cards', title: 'Incidents Needing Attention', sectionLabel: 'Active Incident Queue' },
  },
  'problem-management': {
    'forge-status': { visualType: 'problem-lifecycle-bars', title: 'Problems by Status', sectionLabel: 'Problem Lifecycle' },
    'forge-ticket-aging': { visualType: 'rca-aging-bars', title: 'Problem Aging and RCA Risk', sectionLabel: 'RCA Aging' },
    'forge-average-time-status': { visualType: 'rca-duration-bars', title: 'RCA Stage Duration Proxy', sectionLabel: 'Root Cause Progress' },
    'forge-reports': { visualType: 'knowledge-drilldowns', title: 'Known Errors and RCA Drilldowns', sectionLabel: 'Known Error Evidence' },
    'forge-open-work': { visualType: 'problem-register-cards', title: 'Open Problem Register', sectionLabel: 'Problem Register' },
  },
  'change-management': {
    'forge-roadmap': { visualType: 'change-calendar', title: 'Change Calendar', sectionLabel: 'Scheduled Changes' },
    'forge-status': { visualType: 'approval-bars', title: 'Approval and Implementation Status', sectionLabel: 'Approval Flow' },
    'forge-priority': { visualType: 'emergency-donut', title: 'Emergency Change Mix', sectionLabel: 'Change Risk' },
    'forge-overdue': { visualType: 'approval-delay-bars', title: 'Delayed Approvals', sectionLabel: 'Approval Delays' },
    'forge-created-resolved': { visualType: 'change-volume-trend', title: 'Change Volume Trend', sectionLabel: 'Change Throughput' },
  },
  'knowledge-dashboard': {
    'forge-reports': { visualType: 'knowledge-drilldowns', title: 'Knowledge Gaps and Articles', sectionLabel: 'Knowledge Effectiveness' },
    'forge-projects': { visualType: 'knowledge-coverage-bars', title: 'Knowledge Coverage by Project', sectionLabel: 'Coverage' },
    'forge-open-work': { visualType: 'knowledge-gap-cards', title: 'Requests Suggesting Knowledge Gaps', sectionLabel: 'Missing Content Signals' },
    'forge-ticket-aging': { visualType: 'self-service-aging-bars', title: 'Aging Requests Without Deflection', sectionLabel: 'Deflection Opportunities' },
  },
  'enterprise-demand': {
    'forge-projects': { visualType: 'demand-bars', title: 'Request Volume by Project', sectionLabel: 'Demand Distribution' },
    'forge-created-resolved': { visualType: 'monthly-demand-trend', title: 'Ticket Trend by Month', sectionLabel: 'Demand Trend' },
    'forge-status': { visualType: 'category-bars', title: 'Requests by Work Category', sectionLabel: 'Demand Categories' },
    'forge-priority': { visualType: 'demand-urgency-donut', title: 'Demand Urgency Mix', sectionLabel: 'Demand Urgency' },
  },
  'workforce-capacity': {
    'forge-projects': { visualType: 'capacity-bars', title: 'Tickets by Team / Project', sectionLabel: 'Team Capacity' },
    'forge-open-work': { visualType: 'capacity-action-cards', title: 'Workload Detail', sectionLabel: 'Workload Detail' },
    'forge-status': { visualType: 'queue-volume-bars', title: 'Queue Volume by Status', sectionLabel: 'Queue Volume' },
    'forge-ticket-aging': { visualType: 'backlog-aging-bars', title: 'Backlog Aging', sectionLabel: 'Backlog Risk' },
  },
  'engineering-portfolio-health': {
    'forge-environment': { visualType: 'portfolio-scorecard', title: 'Engineering Portfolio Health', sectionLabel: 'Portfolio Health' },
    'forge-roadmap': { visualType: 'release-readiness-timeline', title: 'Release Readiness Timeline', sectionLabel: 'Release Readiness' },
    'forge-status': { visualType: 'project-status-bars', title: 'Project Status Distribution', sectionLabel: 'Project Health' },
    'forge-priority': { visualType: 'blocker-donut', title: 'Open Blockers and Defect Risk', sectionLabel: 'Risk Mix' },
  },
  'scrum-sprint-health': {
    'forge-sprint-health': { visualType: 'sprint-donut', title: 'Sprint Completion Health', sectionLabel: 'Sprint Health' },
    'forge-sprint-burndown': { visualType: 'burndown-columns', title: 'Sprint Burndown', sectionLabel: 'Burndown' },
    'forge-status': { visualType: 'sprint-status-bars', title: 'Open Issues by Status', sectionLabel: 'Sprint Flow' },
    'forge-overdue': { visualType: 'blocked-bars', title: 'Blocked or At-Risk Stories', sectionLabel: 'Blocked Work' },
  },
  'scrum-velocity': {
    'forge-sprint-burndown': { visualType: 'velocity-columns', title: 'Velocity Trend', sectionLabel: 'Velocity' },
    'forge-created-resolved': { visualType: 'velocity-trend', title: 'Completed Story Trend', sectionLabel: 'Predictability Trend' },
    'forge-sprint-health': { visualType: 'predictability-donut', title: 'Sprint Predictability', sectionLabel: 'Predictability' },
  },
  'kanban-flow-health': {
    'forge-status': { visualType: 'flow-bars', title: 'Work by Status', sectionLabel: 'Flow State' },
    'forge-created-resolved': { visualType: 'throughput-trend', title: 'Throughput Trend', sectionLabel: 'Throughput' },
    'forge-average-time-status': { visualType: 'cycle-time-bars', title: 'Cycle Time Proxy', sectionLabel: 'Cycle Time' },
    'forge-ticket-aging': { visualType: 'bottleneck-aging-bars', title: 'Queue Aging Bottlenecks', sectionLabel: 'Bottlenecks' },
  },
  'kanban-wip': {
    'forge-status': { visualType: 'wip-bars', title: 'Active WIP by Status', sectionLabel: 'WIP Load' },
    'forge-projects': { visualType: 'wip-distribution-bars', title: 'Work Distribution', sectionLabel: 'Distribution' },
    'forge-overdue': { visualType: 'wip-breach-bars', title: 'WIP Breach Risk', sectionLabel: 'WIP Risk' },
  },
  'kanban-aging-work': {
    'forge-ticket-aging': { visualType: 'stagnant-aging-bars', title: 'Oldest Work Items', sectionLabel: 'Stagnant Work' },
    'forge-overdue': { visualType: 'aging-risk-bars', title: 'Aging Threshold Risk', sectionLabel: 'Threshold Risk' },
    'forge-average-time-status': { visualType: 'aging-duration-bars', title: 'Average Work Age', sectionLabel: 'Average Age' },
  },
};

function createProfile({
  title,
  level,
  domain,
  keywords,
  metrics,
  questions,
  kpis,
  priorityRoles,
  gadgetTitles = {},
  visuals = {},
}) {
  return {
    title,
    level,
    domain,
    keywords: [title, ...(keywords || [])].map(value => String(value).toLowerCase()),
    metrics,
    questions,
    kpis,
    priorityRoles,
    gadgetTitles: { ...DEFAULT_GADGET_TITLES, ...gadgetTitles },
    visuals: { ...DEFAULT_GADGET_VISUALS, ...visuals },
  };
}

const DASHBOARD_PROFILES = {
  'enterprise-service-health': createProfile({
    title: 'Enterprise Service Health Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['overall health', 'service availability', 'systemic issues', 'service levels'],
    metrics: ['Total requests', 'Open vs resolved', 'Major incidents', 'Service availability', 'SLA trend', 'Escalation trend', 'CSAT trend'],
    questions: ['What is the current enterprise service health?', 'Are service levels improving or deteriorating?', 'Are there systemic issues?'],
    kpis: ['SLA compliance %', 'MTTR', 'Service availability %', 'Resolution rate %', 'CSAT score'],
    priorityRoles: ['forge-environment', 'forge-created-resolved', 'forge-escalations', 'forge-priority', 'forge-status', 'forge-ticket-aging'],
    gadgetTitles: {
      'forge-environment': 'Enterprise Health Scorecard',
      'forge-created-resolved': 'Demand vs Resolution Trend',
      'forge-escalations': 'SLA Compliance and Escalation Trend',
      'forge-priority': 'Major Incident and Severity Mix',
      'forge-status': 'Enterprise Work Health by Status',
      'forge-ticket-aging': 'Systemic Aging Risk',
    },
    visuals: {
      'forge-environment': 'executive-scorecard',
      'forge-created-resolved': 'dual-trend',
      'forge-escalations': 'sla-donut',
      'forge-priority': 'severity-donut',
    },
  }),
  'enterprise-demand': createProfile({
    title: 'Enterprise Demand Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['requests by project', 'business unit', 'channel usage', 'regional request volume'],
    metrics: ['Requests by project', 'Requests by category', 'Ticket trend by month', 'Channel usage', 'Regional request volume'],
    questions: ['Which areas generate the most support demand?', 'Are demand patterns changing?', 'Which teams may need scaling?'],
    kpis: ['Request growth %', 'Portal adoption %', 'Demand distribution %'],
    priorityRoles: ['forge-projects', 'forge-created-resolved', 'forge-status', 'forge-priority', 'forge-open-work', 'forge-reports'],
    gadgetTitles: {
      'forge-projects': 'Demand by Project and Service',
      'forge-created-resolved': 'Monthly Demand Pattern',
      'forge-status': 'Demand by Work Stage',
      'forge-priority': 'Demand Urgency Mix',
      'forge-open-work': 'High-Demand Request Detail',
      'forge-reports': 'Demand Drilldown Reports',
    },
    visuals: {
      'forge-projects': 'demand-bars',
      'forge-created-resolved': 'monthly-trend',
      'forge-status': 'category-bars',
    },
  }),
  'enterprise-sla': createProfile({
    title: 'Enterprise SLA Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['sla achievement by project', 'breached requests', 'response times', 'resolution times'],
    metrics: ['SLA achievement by project', 'SLA achievement by team', 'Breached requests', 'Response time', 'Resolution time'],
    questions: ['Which teams miss targets?', 'Are breaches increasing?', 'Which services create risk?'],
    kpis: ['Response SLA %', 'Resolution SLA %', 'Breach %'],
    priorityRoles: ['forge-escalations', 'forge-overdue', 'forge-average-time-status', 'forge-created-resolved', 'forge-ticket-aging', 'forge-open-work'],
    gadgetTitles: {
      'forge-escalations': 'SLA Achievement and Breach Mix',
      'forge-overdue': 'Breached Requests by Project',
      'forge-average-time-status': 'Response and Resolution Time Proxy',
      'forge-created-resolved': 'SLA Trend Signal',
      'forge-ticket-aging': 'Requests Nearing Breach',
      'forge-open-work': 'Breach Follow-Up Queue',
    },
    visuals: {
      'forge-escalations': 'sla-donut',
      'forge-overdue': 'breach-bars',
      'forge-average-time-status': 'response-bars',
    },
  }),
  'enterprise-incident': createProfile({
    title: 'Enterprise Incident Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['major incidents', 'severity distribution', 'impacted services'],
    metrics: ['Major incidents', 'Severity distribution', 'Escalation counts', 'Incident trend', 'Impacted services'],
    questions: ['Which critical incidents require attention?', 'Which services fail repeatedly?'],
    kpis: ['MTTR', 'Incident recurrence %', 'Escalation %'],
    priorityRoles: ['forge-priority', 'forge-escalations', 'forge-created-resolved', 'forge-status', 'forge-ticket-aging', 'forge-reports'],
    gadgetTitles: {
      'forge-priority': 'Incident Severity Distribution',
      'forge-escalations': 'Active Escalation Pressure',
      'forge-created-resolved': 'Incident Volume Trend',
      'forge-status': 'Incident Restoration Flow',
      'forge-ticket-aging': 'Aging Critical Incidents',
      'forge-reports': 'Major Incident Drilldowns',
    },
    visuals: {
      'forge-priority': 'severity-donut',
      'forge-escalations': 'incident-risk-donut',
      'forge-created-resolved': 'incident-trend',
    },
  }),
  'enterprise-problem': createProfile({
    title: 'Enterprise Problem Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['known errors', 'rca completion', 'recurring incidents'],
    metrics: ['Problems by service', 'Known errors', 'Problem aging', 'RCA completion', 'Recurring incidents'],
    questions: ['What recurring problems exist?', 'Are root causes being addressed?'],
    kpis: ['RCA completion %', 'Problem closure %', 'Recurrence %'],
    priorityRoles: ['forge-status', 'forge-ticket-aging', 'forge-average-time-status', 'forge-created-resolved', 'forge-reports', 'forge-open-work'],
    gadgetTitles: {
      'forge-status': 'Problem Lifecycle Status',
      'forge-ticket-aging': 'Problem Aging and RCA Risk',
      'forge-average-time-status': 'RCA Time in Stage',
      'forge-created-resolved': 'Problem Closure Trend',
      'forge-reports': 'Known Error and RCA Reports',
      'forge-open-work': 'Open Problem Register',
    },
    visuals: {
      'forge-status': 'lifecycle-bars',
      'forge-ticket-aging': 'rca-aging-bars',
      'forge-average-time-status': 'rca-duration-bars',
    },
  }),
  'enterprise-change': createProfile({
    title: 'Enterprise Change Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['change volume', 'emergency changes', 'failed changes', 'pending approvals', 'rollbacks'],
    metrics: ['Change volume', 'Emergency changes', 'Failed changes', 'Pending approvals', 'Rollbacks'],
    questions: ['Are changes introducing instability?', 'Are emergency changes increasing?'],
    kpis: ['Change success %', 'Emergency change %', 'Rollback %'],
    priorityRoles: ['forge-roadmap', 'forge-status', 'forge-created-resolved', 'forge-priority', 'forge-overdue', 'forge-reports'],
    gadgetTitles: {
      'forge-roadmap': 'Change and Release Calendar',
      'forge-status': 'Approval and Implementation Status',
      'forge-created-resolved': 'Change Volume Trend',
      'forge-priority': 'Emergency Change Mix',
      'forge-overdue': 'Delayed Change Approvals',
      'forge-reports': 'Change Risk Drilldowns',
    },
    visuals: {
      'forge-roadmap': 'change-calendar',
      'forge-status': 'approval-bars',
      'forge-priority': 'emergency-donut',
    },
  }),
  'service-portfolio': createProfile({
    title: 'Service Portfolio Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['service demand', 'service usage', 'service-specific csat'],
    metrics: ['Service demand', 'Service availability', 'Service usage', 'Service-specific CSAT'],
    questions: ['Which services perform poorly?', 'Which services are most consumed?'],
    kpis: ['Service utilization %', 'Service availability %', 'Service satisfaction %'],
    priorityRoles: ['forge-projects', 'forge-status', 'forge-created-resolved', 'forge-escalations', 'forge-priority', 'forge-reports'],
  }),
  'workforce-capacity': createProfile({
    title: 'Workforce & Capacity Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['team workload', 'staffing utilization', 'work distribution'],
    metrics: ['Team workload', 'Queue volumes', 'Staffing utilization', 'Work distribution'],
    questions: ['Which teams are overloaded?', 'Do staffing levels support demand?'],
    kpis: ['Utilization %', 'Queue backlog %', 'Workload balance %'],
    priorityRoles: ['forge-projects', 'forge-open-work', 'forge-status', 'forge-ticket-aging', 'forge-average-time-status', 'forge-priority'],
  }),
  'customer-experience': createProfile({
    title: 'Customer Experience Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['csat trend', 'survey results', 'portal usage', 'knowledge usage'],
    metrics: ['CSAT trend', 'Escalation trend', 'Survey results', 'Portal usage', 'Knowledge usage'],
    questions: ['Are customers satisfied?', 'Is self-service reducing demand?'],
    kpis: ['CSAT', 'Escalation rate', 'Knowledge deflection %'],
    priorityRoles: ['forge-escalations', 'forge-created-resolved', 'forge-reports', 'forge-ticket-aging', 'forge-status', 'forge-priority'],
  }),
  'asset-configuration': createProfile({
    title: 'Asset & Configuration Dashboard',
    level: 'Enterprise',
    domain: 'Service Management',
    keywords: ['asset inventory', 'license usage', 'warranty expiration', 'configuration'],
    metrics: ['Asset inventory', 'Asset allocation', 'License usage', 'Warranty expiration'],
    questions: ['Which assets need attention?', 'Are assets compliant?'],
    kpis: ['Asset utilization %', 'Compliance %'],
    priorityRoles: ['forge-projects', 'forge-status', 'forge-overdue', 'forge-ticket-aging', 'forge-priority', 'forge-reports'],
  }),
  'service-desk-operations': createProfile({
    title: 'Service Desk Operations Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['open tickets', 'queue health', 'sla at risk'],
    metrics: ['Open tickets', 'Tickets by priority', 'Aging tickets', 'Queue health', 'SLA at risk'],
    questions: ['What requires immediate action?', 'Which queues need balancing?'],
    kpis: ['Resolution rate %', 'First response time', 'Queue aging'],
    priorityRoles: ['forge-open-work', 'forge-status', 'forge-priority', 'forge-ticket-aging', 'forge-escalations', 'forge-average-time-status'],
  }),
  'incident-management': createProfile({
    title: 'Incident Management Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['active incidents', 'severity distribution', 'resolution trends'],
    metrics: ['Active incidents', 'Severity distribution', 'Escalations', 'Resolution trends'],
    questions: ['Which incidents require attention?', 'Are escalations increasing?'],
    kpis: ['MTTR', 'Closure %', 'Escalation %'],
    priorityRoles: ['forge-priority', 'forge-escalations', 'forge-status', 'forge-created-resolved', 'forge-ticket-aging', 'forge-open-work'],
  }),
  'problem-management': createProfile({
    title: 'Problem Management Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['problems by status', 'known errors', 'rca status'],
    metrics: ['Problems by status', 'Known errors', 'Problem aging', 'RCA status'],
    questions: ['Are recurring issues increasing?', 'Are root causes resolved?'],
    kpis: ['Problem closure %', 'RCA completion %'],
    priorityRoles: ['forge-status', 'forge-ticket-aging', 'forge-average-time-status', 'forge-reports', 'forge-created-resolved', 'forge-open-work'],
  }),
  'change-management': createProfile({
    title: 'Change Management Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['scheduled changes', 'approval status', 'rollback'],
    metrics: ['Scheduled changes', 'Emergency changes', 'Rollbacks', 'Approval status'],
    questions: ['Which changes create risk?', 'Are approvals delayed?'],
    kpis: ['Change success %', 'Rollback %'],
    priorityRoles: ['forge-roadmap', 'forge-status', 'forge-overdue', 'forge-priority', 'forge-created-resolved', 'forge-reports'],
  }),
  'agent-performance': createProfile({
    title: 'Agent Performance Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['tickets resolved', 'workload distribution', 'average handling time'],
    metrics: ['Tickets resolved', 'Workload distribution', 'Reopened tickets', 'Average handling time'],
    questions: ['Is workload balanced?', 'Is productivity improving?'],
    kpis: ['Productivity %', 'Reopen %', 'CSAT'],
    priorityRoles: ['forge-projects', 'forge-open-work', 'forge-average-time-status', 'forge-status', 'forge-created-resolved', 'forge-priority'],
  }),
  'sla-monitoring': createProfile({
    title: 'SLA Monitoring Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['sla achievement', 'breached tickets', 'approaching breach'],
    metrics: ['SLA achievement', 'Breached tickets', 'Tickets approaching breach'],
    questions: ['Are SLAs at risk?', 'Where should escalation happen?'],
    kpis: ['SLA compliance %', 'Breach %'],
    priorityRoles: ['forge-escalations', 'forge-overdue', 'forge-ticket-aging', 'forge-average-time-status', 'forge-open-work', 'forge-created-resolved'],
  }),
  'knowledge-dashboard': createProfile({
    title: 'Knowledge Dashboard',
    level: 'Team',
    domain: 'Service Management',
    keywords: ['article views', 'search trends', 'missing content'],
    metrics: ['Article views', 'Feedback', 'Search trends', 'Missing content'],
    questions: ['Are articles helping users?', 'Which content is missing?'],
    kpis: ['Knowledge deflection %', 'Search success %'],
    priorityRoles: ['forge-reports', 'forge-projects', 'forge-open-work', 'forge-status', 'forge-ticket-aging', 'forge-created-resolved'],
  }),
  'engineering-portfolio-health': createProfile({
    title: 'Engineering Portfolio Health Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['projects on track', 'at risk', 'dependency status'],
    metrics: ['Projects on track vs at risk', 'Open blockers', 'Release readiness', 'Milestone completion', 'Defect trends', 'Dependency status'],
    questions: ['Which projects need intervention?', 'Which projects are at risk?', 'Are strategic goals being met?'],
    kpis: ['Project health score', 'On-time delivery %', 'Milestone completion %', 'Delivery predictability %'],
    priorityRoles: ['forge-environment', 'forge-roadmap', 'forge-status', 'forge-priority', 'forge-created-resolved', 'forge-ticket-aging'],
  }),
  'enterprise-delivery': createProfile({
    title: 'Enterprise Delivery Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['team throughput', 'velocity trend', 'cycle time trend', 'lead time trend'],
    metrics: ['Team throughput', 'Story completion trend', 'Velocity trend', 'Cycle time trend', 'Lead time trend', 'Completed work by team'],
    questions: ['Which teams deliver consistently?', 'Is delivery improving or declining?', 'Which teams need support?'],
    kpis: ['Delivery consistency %', 'Throughput', 'Average cycle time', 'Average lead time'],
    priorityRoles: ['forge-created-resolved', 'forge-sprint-health', 'forge-average-time-status', 'forge-projects', 'forge-status', 'forge-reports'],
  }),
  'release-portfolio': createProfile({
    title: 'Release Portfolio Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['upcoming releases', 'failed deployments', 'release blockers'],
    metrics: ['Upcoming releases', 'Release progress', 'Failed deployments', 'Open release blockers', 'Release completion', 'Deployment status'],
    questions: ['Which releases are at risk?', 'Are deployments succeeding?', 'What is blocking releases?'],
    kpis: ['Release success %', 'Deployment success %', 'Release readiness %'],
    priorityRoles: ['forge-roadmap', 'forge-priority', 'forge-status', 'forge-created-resolved', 'forge-open-work', 'forge-reports'],
  }),
  'quality-defect': createProfile({
    title: 'Quality & Defect Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['defects by severity', 'critical defects', 'escaped defects'],
    metrics: ['Defects by severity', 'Critical defects', 'Defect trend', 'Reopened defects', 'Escaped defects', 'Defect aging'],
    questions: ['Which products have quality issues?', 'Are defects increasing?', 'Are fixes effective?'],
    kpis: ['Defect leakage %', 'Defect density', 'Reopen %', 'Escaped defect rate %'],
    priorityRoles: ['forge-priority', 'forge-ticket-aging', 'forge-created-resolved', 'forge-status', 'forge-overdue', 'forge-reports'],
  }),
  'devops': createProfile({
    title: 'DevOps Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['deployment frequency', 'build success', 'pipeline success'],
    metrics: ['Deployment frequency', 'Build success rate', 'Failed deployments', 'Recovery time', 'Pipeline success rate'],
    questions: ['Is deployment healthy?', 'Are builds failing frequently?', 'Is deployment speed improving?'],
    kpis: ['Deployment success %', 'Mean recovery time', 'Deployment frequency'],
    priorityRoles: ['forge-created-resolved', 'forge-roadmap', 'forge-priority', 'forge-status', 'forge-overdue', 'forge-reports'],
  }),
  'engineering-capacity': createProfile({
    title: 'Engineering Capacity Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['resource allocation', 'planned vs actual effort', 'capacity trends'],
    metrics: ['Team utilization', 'Resource allocation', 'Team workload', 'Capacity trends', 'Planned vs actual effort'],
    questions: ['Are teams overloaded?', 'Is staffing sufficient?', 'Is work evenly distributed?'],
    kpis: ['Utilization %', 'Workload balance %', 'Capacity variance %'],
    priorityRoles: ['forge-projects', 'forge-open-work', 'forge-sprint-health', 'forge-status', 'forge-average-time-status', 'forge-ticket-aging'],
  }),
  'technical-debt': createProfile({
    title: 'Technical Debt Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['technical debt stories', 'refactoring backlog', 'high-risk modules'],
    metrics: ['Technical debt stories', 'Refactoring backlog', 'Aging technical debt', 'Debt by component', 'High-risk modules'],
    questions: ['Is maintainability deteriorating?', 'Which areas require refactoring?'],
    kpis: ['Technical debt ratio %', 'Technical debt reduction %', 'Aging debt %'],
    priorityRoles: ['forge-ticket-aging', 'forge-open-work', 'forge-priority', 'forge-status', 'forge-average-time-status', 'forge-reports'],
  }),
  'product-delivery': createProfile({
    title: 'Product Delivery Dashboard',
    level: 'Enterprise',
    domain: 'Software',
    keywords: ['epic completion', 'roadmap progress', 'delayed features'],
    metrics: ['Epic completion', 'Feature completion', 'Roadmap progress', 'Planned vs delivered features', 'Delayed features'],
    questions: ['Are product goals being achieved?', 'Which features are delayed?'],
    kpis: ['Feature completion %', 'Delivery predictability %', 'On-time feature delivery %'],
    priorityRoles: ['forge-roadmap', 'forge-status', 'forge-created-resolved', 'forge-sprint-health', 'forge-open-work', 'forge-reports'],
  }),
  'scrum-sprint-health': createProfile({
    title: 'Sprint Health Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['sprint progress', 'burndown', 'scope changes'],
    metrics: ['Sprint progress', 'Story points committed', 'Story points completed', 'Sprint burndown', 'Blocked stories', 'Scope changes'],
    questions: ['Is the sprint on track?', 'What work is blocked?', 'Has scope changed?'],
    kpis: ['Sprint completion %', 'Burndown adherence %', 'Scope change %'],
    priorityRoles: ['forge-sprint-health', 'forge-sprint-burndown', 'forge-status', 'forge-overdue', 'forge-priority', 'forge-open-work'],
    visuals: {
      'forge-sprint-health': 'sprint-donut',
      'forge-sprint-burndown': 'burndown-columns',
      'forge-status': 'sprint-status-bars',
    },
  }),
  'scrum-velocity': createProfile({
    title: 'Velocity Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['story points completed', 'average velocity', 'velocity variance'],
    metrics: ['Story points completed', 'Velocity trend', 'Average velocity', 'Velocity variance'],
    questions: ['How much work can be committed next sprint?', 'Is delivery becoming predictable?'],
    kpis: ['Average velocity', 'Sprint predictability %', 'Velocity consistency %'],
    priorityRoles: ['forge-sprint-burndown', 'forge-created-resolved', 'forge-sprint-health', 'forge-status', 'forge-projects', 'forge-reports'],
    visuals: {
      'forge-sprint-burndown': 'velocity-columns',
      'forge-created-resolved': 'velocity-trend',
      'forge-sprint-health': 'predictability-donut',
    },
  }),
  'scrum-sprint-capacity': createProfile({
    title: 'Sprint Capacity Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['team capacity', 'availability', 'capacity utilization'],
    metrics: ['Team capacity', 'Availability', 'Assigned work', 'Capacity utilization'],
    questions: ['Is work distributed properly?', 'Is the sprint overloaded?'],
    kpis: ['Capacity utilization %', 'Workload balance %'],
    priorityRoles: ['forge-projects', 'forge-open-work', 'forge-sprint-health', 'forge-status', 'forge-average-time-status', 'forge-priority'],
  }),
  'scrum-backlog-health': createProfile({
    title: 'Backlog Health Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['backlog size', 'unestimated stories', 'ready stories'],
    metrics: ['Backlog size', 'Unestimated stories', 'Technical debt stories', 'Priority distribution', 'Ready stories'],
    questions: ['Is enough work prepared?', 'Is backlog quality sufficient?'],
    kpis: ['Backlog readiness %', 'Estimation completion %'],
    priorityRoles: ['forge-open-work', 'forge-priority', 'forge-status', 'forge-ticket-aging', 'forge-reports', 'forge-projects'],
  }),
  'scrum-defect': createProfile({
    title: 'Defect Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['open defects', 'critical defects', 'reopened defects'],
    metrics: ['Open defects', 'Critical defects', 'Defect aging', 'Reopened defects'],
    questions: ['Are quality issues increasing?', 'Are defects being resolved?'],
    kpis: ['Defect leakage %', 'Reopen %'],
    priorityRoles: ['forge-priority', 'forge-ticket-aging', 'forge-created-resolved', 'forge-status', 'forge-overdue', 'forge-reports'],
  }),
  'scrum-qa-test': createProfile({
    title: 'QA/Test Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['test execution', 'passed tests', 'automation coverage'],
    metrics: ['Test execution progress', 'Passed tests', 'Failed tests', 'Regression status', 'Automation coverage'],
    questions: ['Is testing complete?', 'Which areas are failing?'],
    kpis: ['Test pass %', 'Automation coverage %'],
    priorityRoles: ['forge-status', 'forge-priority', 'forge-ticket-aging', 'forge-created-resolved', 'forge-open-work', 'forge-reports'],
  }),
  'scrum-release': createProfile({
    title: 'Release Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['release progress', 'release blockers', 'deployment status'],
    metrics: ['Release progress', 'Release blockers', 'Deployment status', 'Open defects'],
    questions: ['Is the release ready?', 'What risks remain?'],
    kpis: ['Release success %', 'Deployment success %'],
    priorityRoles: ['forge-roadmap', 'forge-priority', 'forge-status', 'forge-created-resolved', 'forge-open-work', 'forge-reports'],
  }),
  'scrum-team-performance': createProfile({
    title: 'Team Performance Dashboard',
    level: 'Team - Scrum',
    domain: 'Software',
    keywords: ['work completed by developer', 'review turnaround', 'blocked work'],
    metrics: ['Work completed by developer', 'Average completion time', 'Review turnaround', 'Blocked work'],
    questions: ['Is workload balanced?', 'Are bottlenecks appearing?'],
    kpis: ['Productivity %', 'Cycle time', 'Throughput'],
    priorityRoles: ['forge-projects', 'forge-created-resolved', 'forge-average-time-status', 'forge-overdue', 'forge-status', 'forge-open-work'],
  }),
  'kanban-flow-health': createProfile({
    title: 'Flow Health Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['work by status', 'queue sizes', 'bottlenecks'],
    metrics: ['Work by status', 'Throughput', 'Cycle time', 'Lead time', 'Queue sizes'],
    questions: ['Is work moving smoothly?', 'Where are bottlenecks?'],
    kpis: ['Flow efficiency %', 'Average cycle time'],
    priorityRoles: ['forge-status', 'forge-created-resolved', 'forge-average-time-status', 'forge-ticket-aging', 'forge-open-work', 'forge-priority'],
    visuals: {
      'forge-status': 'flow-bars',
      'forge-created-resolved': 'throughput-trend',
      'forge-average-time-status': 'cycle-time-bars',
    },
  }),
  'kanban-throughput': createProfile({
    title: 'Throughput Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['completed items/week', 'throughput trends', 'completion trends'],
    metrics: ['Completed items/week', 'Throughput trends', 'Completion trends'],
    questions: ['Is delivery stable?', 'Is output improving?'],
    kpis: ['Average throughput', 'Delivery consistency %'],
    priorityRoles: ['forge-created-resolved', 'forge-status', 'forge-projects', 'forge-average-time-status', 'forge-reports', 'forge-open-work'],
    visuals: {
      'forge-created-resolved': 'throughput-trend',
      'forge-status': 'completion-bars',
      'forge-projects': 'team-throughput-bars',
    },
  }),
  'kanban-cycle-time': createProfile({
    title: 'Cycle Time Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['average cycle time', 'median cycle time', 'slowest work items'],
    metrics: ['Average cycle time', 'Median cycle time', 'Slowest work items'],
    questions: ['How long does work take?', 'Which work items take too long?'],
    kpis: ['Average cycle time', 'Cycle time variation %'],
    priorityRoles: ['forge-average-time-status', 'forge-ticket-aging', 'forge-created-resolved', 'forge-open-work', 'forge-status', 'forge-reports'],
  }),
  'kanban-lead-time': createProfile({
    title: 'Lead Time Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['lead time trend', 'lead time by issue type'],
    metrics: ['Lead time', 'Lead time trend', 'Lead time by issue type'],
    questions: ['How long does delivery take from request to completion?'],
    kpis: ['Average lead time', 'Lead time consistency %'],
    priorityRoles: ['forge-created-resolved', 'forge-average-time-status', 'forge-ticket-aging', 'forge-status', 'forge-open-work', 'forge-reports'],
  }),
  'kanban-wip': createProfile({
    title: 'WIP Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['active work items', 'wip limit breaches', 'queue size'],
    metrics: ['Active work items', 'WIP limit breaches', 'Queue size'],
    questions: ['Is anyone overloaded?', 'Are WIP limits violated?'],
    kpis: ['WIP compliance %'],
    priorityRoles: ['forge-status', 'forge-projects', 'forge-open-work', 'forge-overdue', 'forge-ticket-aging', 'forge-priority'],
  }),
  'kanban-blockers': createProfile({
    title: 'Blockers Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['blocked items', 'dependency count', 'blocked duration'],
    metrics: ['Blocked items', 'Dependency count', 'Blocked duration'],
    questions: ['What prevents progress?', 'Which blockers need escalation?'],
    kpis: ['Blocker resolution time', 'Dependency resolution %'],
    priorityRoles: ['forge-overdue', 'forge-ticket-aging', 'forge-priority', 'forge-open-work', 'forge-status', 'forge-reports'],
  }),
  'kanban-aging-work': createProfile({
    title: 'Aging Work Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['oldest items', 'aging trends', 'aging distribution'],
    metrics: ['Oldest items', 'Aging trends', 'Aging distribution'],
    questions: ['Which work items are stagnant?'],
    kpis: ['Average work age', 'Aging compliance %'],
    priorityRoles: ['forge-ticket-aging', 'forge-overdue', 'forge-average-time-status', 'forge-open-work', 'forge-status', 'forge-priority'],
  }),
  'kanban-team-performance': createProfile({
    title: 'Team Performance Dashboard',
    level: 'Team - Kanban',
    domain: 'Software',
    keywords: ['throughput by developer', 'cycle time by developer', 'work distribution'],
    metrics: ['Throughput by developer', 'Cycle time by developer', 'Work distribution'],
    questions: ['Is workload balanced?', 'Is output improving?'],
    kpis: ['Throughput', 'Productivity %', 'Flow efficiency %'],
    priorityRoles: ['forge-projects', 'forge-created-resolved', 'forge-average-time-status', 'forge-status', 'forge-open-work', 'forge-reports'],
  }),
  operational: createProfile({
    title: 'Default Operational Dashboard',
    level: 'Default',
    domain: 'General',
    keywords: ['default', 'operations'],
    metrics: ['Open work', 'Status distribution', 'Priority distribution', 'Created vs resolved', 'Aging work'],
    questions: ['What work is active?', 'Where is delivery risk?'],
    kpis: ['Open work', 'Resolution rate', 'SLA risk'],
    priorityRoles: ['forge-environment', 'forge-open-work', 'forge-status', 'forge-priority', 'forge-created-resolved', 'forge-ticket-aging'],
  }),
};

function mergeProfiles(selectedProfiles) {
  const [primaryKey, primaryProfile] = selectedProfiles[0];
  const mergedRoles = Array.from(new Set(selectedProfiles.flatMap(([, profile]) => profile.priorityRoles)));

  return {
    profile: primaryKey,
    title: selectedProfiles.length === 1 ? primaryProfile.title : 'Multi-focus Dashboard',
    level: selectedProfiles.length === 1 ? primaryProfile.level : 'Multi-focus',
    domain: selectedProfiles.length === 1 ? primaryProfile.domain : primaryProfile.domain,
    metrics: Array.from(new Set(selectedProfiles.flatMap(([, profile]) => profile.metrics))).slice(0, 8),
    questions: Array.from(new Set(selectedProfiles.flatMap(([, profile]) => profile.questions))).slice(0, 4),
    kpis: Array.from(new Set(selectedProfiles.flatMap(([, profile]) => profile.kpis))).slice(0, 5),
    priorityRoles: mergedRoles.slice(0, 6),
    gadgetTitles: Object.assign({}, ...selectedProfiles.map(([, profile]) => profile.gadgetTitles)),
    visuals: Object.assign({}, ...selectedProfiles.map(([, profile]) => profile.visuals)),
    sectionLabels: Object.assign({}, ...selectedProfiles.map(([profileKey, profile]) => (
      Object.fromEntries(profile.priorityRoles.map(role => [
        role,
        PROFILE_ROLE_OVERRIDES[profileKey]?.[role]?.sectionLabel || ROLE_SECTION_LABELS[role] || 'Dashboard Section',
      ]))
    ))),
  };
}

export function inferDashboardIntent(prompt, industry, selectedValue = '') {
  const normalizedPrompt = String(prompt || '').toLowerCase();
  const normalizedValue = String(selectedValue || '').toLowerCase();
  const exactProfile = DASHBOARD_PROFILES[normalizedValue];
  const matches = exactProfile
    ? [[normalizedValue, exactProfile]]
    : Object.entries(DASHBOARD_PROFILES)
      .filter(([key]) => key !== 'operational')
      .filter(([, value]) => value.keywords.some(keyword => normalizedPrompt.includes(keyword)));

  const selectedProfiles = matches.length > 0 ? matches : [['operational', DASHBOARD_PROFILES.operational]];
  const merged = mergeProfiles(selectedProfiles);

  return {
    ...merged,
    prompt: String(prompt || '').trim(),
    industry,
  };
}

export function orderDashboardGadgetPlans(plans, dashboardIntent) {
  const roles = dashboardIntent?.priorityRoles || DASHBOARD_PROFILES.operational.priorityRoles;
  const byRole = new Map(plans.map(plan => [plan.role, plan]));

  return roles
    .map(role => byRole.get(role))
    .filter(Boolean)
    .map(plan => ({
      ...PROFILE_ROLE_OVERRIDES[dashboardIntent?.profile]?.[plan.role],
      ...plan,
      title: PROFILE_ROLE_OVERRIDES[dashboardIntent?.profile]?.[plan.role]?.title || dashboardIntent?.gadgetTitles?.[plan.role] || plan.title,
      subtitle: dashboardIntent?.questions?.[0] || '',
      visualType: PROFILE_ROLE_OVERRIDES[dashboardIntent?.profile]?.[plan.role]?.visualType || dashboardIntent?.visuals?.[plan.role] || DEFAULT_GADGET_VISUALS[plan.role] || 'standard',
      sectionLabel: PROFILE_ROLE_OVERRIDES[dashboardIntent?.profile]?.[plan.role]?.sectionLabel || dashboardIntent?.sectionLabels?.[plan.role] || ROLE_SECTION_LABELS[plan.role] || 'Dashboard Section',
    }));
}

export function buildDashboardName(config, runLabel) {
  const intentTitle = config.dashboardIntent?.title || 'Release Dashboard';
  return `${config.environmentName} - ${intentTitle} (${runLabel})`;
}
